In [1]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)
print(array.shape)
print(array.ndim)
print(array.size)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [2]:
array=np.zeros((3,4))##全一矩阵为ones
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
array=np.arange(10,20,3)##生成有序数列按照指定步长,一个变量的话表示从0到该数字，步长为1
print(array)

[10 13 16 19]


In [4]:
array=np.arange(10,20,3).reshape(2,2)##对数组形状重改，此处为2*2
print(array)

[[10 13]
 [16 19]]


In [6]:
array=np.linspace(1,10,6)
print(array)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [10]:
a=np.array([10,20,30,40])##此处的运算均为单个元素与单个元素的运算，**代表次幂
b=np.arange(1,5)
print(a,"|",b)
c=a*b
print(c)

[10 20 30 40] | [1 2 3 4]
[ 10  40  90 160]


In [11]:
a=np.array([10,20,30,40])
c=10*np.sin(a)##对a的每个值求sin并×10 cos  tan   ((三角函数))
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [19]:
a=np.array([[1,1],
            [0,1]])
b=np.arange(4).reshape((2,2))##矩阵运算
print(b)
c=a*b
c_dot=np.dot(a,b)
print(c_dot)
print("*******")
print(c)

[[0 1]
 [2 3]]
[[2 4]
 [2 3]]
*******
[[0 1]
 [0 3]]


In [26]:
a=np.random.random((2,3))
print(a)

print(np.max(a))
print(np.sum(a))
print(np.min(a))

[[0.53601521 0.47075894 0.17485297]
 [0.68693128 0.89542624 0.08998709]]
0.8954262397379433
2.8539717161434464
0.08998708784711806


In [31]:
print(a)
print("****")
print(np.max(a,axis=0))##axis=0,每一列的最大值（最小值），axis=1,每一行的最大值（最小值）
print(np.sum(a,axis=1))##对行求和，原理相同
print(np.min(a,axis=1))

[[0.53601521 0.47075894 0.17485297]
 [0.68693128 0.89542624 0.08998709]]
****
[0.68693128 0.89542624 0.17485297]
[1.18162711 1.6723446 ]
[0.17485297 0.08998709]


In [47]:
a=np.arange(2,14).reshape(3,4)
print(a)
print("*****")
print(np.argmin(a))
print(np.argmax(a))
print(np.average(a,axis=1))##求矩阵所有元素的平均值,也可以按行按列计算
print(np.median(a))
print(np.cumsum(a).reshape((3,4))) ##与a中元素个数相同，第一个为a中第一个，第二个为a中第一个加第二个，以此类推
print(np.diff(a))##累差，4个数的累差是三个数，因此是3*3
print(a.T)##矩阵转置

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
*****
0
11
[ 3.5  7.5 11.5]
7.5
[[ 2  5  9 14]
 [20 27 35 44]
 [54 65 77 90]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [51]:
a=np.arange(3,15)##                              矩阵索引
b=np.arange(3,15).reshape((3,4))
print(b)
print("*****")
print(b[2][1])
print(b[2,1])
print(b[2,1:3])
print(b[:,2])
print(a[3])


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
*****
12
12
[12 13]
[ 5  9 13]
6


In [56]:
A=np.array([1,1,1])
B=np.array([2,2,2])
C=np.vstack((A,B))##上下合并
D=np.hstack((A,B))##左右合并
print(D)
print(C)
print(A.shape,C.shape,D.shape)
print(A[np.newaxis,:].shape)##在左（行）上加维度，右（列）上加维度

[1 1 1 2 2 2]
[[1 1 1]
 [2 2 2]]
(3,) (2, 3) (6,)
(1, 3)


In [60]:
A=np.array([1,1,1])[:,np.newaxis]##array的合并
B=np.array([2,2,2])[:,np.newaxis]
print(A)
print(":",A.shape)
print("****")
print(B)
print(":",B.shape)
C=np.concatenate((A,B,B,A),axis=1)##对多个array进行合并，用axis进行指定维度的合并
print(C)

[[1]
 [1]
 [1]]
: (3, 1)
****
[[2]
 [2]
 [2]]
: (3, 1)
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [70]:
A=np.arange(12).reshape(3,4)##array的分割
print(A)
print(np.split(A,2,axis=1))##第一个元素是被分割对象，第二个是块数，第三个是方向
print(np.split(A,3,axis=0))
print(np.array_split(A,3,axis=1))##上述情况为均等的分割，这个函数对应不均等分割时的要求
print(np.split(A,3,axis=0))
print(np.vsplit(A,3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [74]:
a=np.arange(4)
a
b=a
c=a.copy()
##等号会让左右两边的变量所有属性相关联，如b=a，改变a的值，b也会变 否则情况如下
a[0]=2
print(a)
print(b)
print(c)

[2 1 2 3]
[2 1 2 3]
[0 1 2 3]
