In [1]:
import pandas as pd
import numpy as np
s=pd.Series([1,3,6,np.nan,44,1])
print(s)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [9]:
dates = pd.date_range('20160101',periods=3)
dates

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03'], dtype='datetime64[ns]', freq='D')

In [10]:
df=pd.DataFrame(np.arange(12).reshape((3,4)),index=dates,columns=['a','b','c','d'])
print(df)

            a  b   c   d
2016-01-01  0  1   2   3
2016-01-02  4  5   6   7
2016-01-03  8  9  10  11


In [8]:
df=pd.DataFrame(np.arange(12).reshape((3,4)))
print(df)
df.shape[1]

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


4

In [13]:
df.shape
df.values
print(df[:,~1])


TypeError: '(slice(None, None, None), -2)' is an invalid key

In [39]:
a=np.array([[1,2,3],[12,3,4],[2,7,8],[5,9,10]]).reshape(-1,4)

In [45]:
a[:,~2]

array([2, 4, 5])

In [41]:
a

array([[ 1,  2,  3, 12],
       [ 3,  4,  2,  7],
       [ 8,  5,  9, 10]])

In [6]:
a,b=df.shape
print(a,b)

3 4


In [53]:
a
print(a.mean(axis=0))

[4.         3.66666667 4.66666667 9.66666667]


In [56]:
import collections

 
print ('Regular dictionary:')
d={}
d['a']='A'
d['c']='C'
d['b']='B'
for k,v in d.items():
    print( k,v)
    
print ('\nOrderedDict:')
d=collections.OrderedDict()
d['a']='A'
d['b']='B'
d['c']='C'
for k,v in d.items():
    print (k,v)

Regular dictionary:
a A
c C
b B

OrderedDict:
a A
b B
c C


In [66]:
data_dict = collections.OrderedDict()

In [68]:
data_dict["qqq"]=[]

In [69]:
data_dict["aaa"]=[]

In [70]:
data_dict["zzz"]=[]

In [75]:
data_dict.app

TypeError: 'collections.OrderedDict' object is not callable

In [72]:
help(collections.OrderedDict)

Help on class OrderedDict in module collections:

class OrderedDict(builtins.dict)
 |  Dictionary that remembers insertion order
 |  
 |  Method resolution order:
 |      OrderedDict
 |      builtins.dict
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __reduce__(...)
 |      Return state information for pickling
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __reversed__(..